Write a program to solve an diagonally dominated tridiagonal system Ax = b,where A is tridiagonal using the algorithm in section 2.3.Input: four one-dimensional arrays a,d,c,bOutput: the solution array x and residual r=Ax-b.Try on three examples of your choice for a,b,c,d with dimensions of A being 5x5, 10x10, 20x20.

in project 3, you need to compute the residual of Ax=b.

The residual is defined as r=Ax-b. 

 

r=0 if x is the exact soln.

in general, r is very very small if x is an good approximation.

In [47]:
import numpy as np

# Solve the problem using thomas algorithm 
def Thomas(a, b, c, d):
    a_new = a
    b_new = b
    c_new = c
    d_new = d
    #an, bn, cn, dn = map(np.array, (a, b, c, d)) # copy arrays
    for i in range(1, len(d)):
        a1 = a_new[i-1]/b_new[i-1]
        b_new[i] = b_new[i] - a1*c_new[i-1] 
        d_new[i] = d_new[i] - a1*d_new[i-1]
    result = b_new
    result[-1] = d_new[-1]/b_new[-1]

    for j in range(len(d)-2, -1, -1):
        result[j] = (d_new[j]-c_new[j]*result[j+1])/b_new[j]
    
    return result


In [154]:
#GENERATE 15x15 array
Ar1 = np.array([[0]*15]*15,dtype = float)
Ar1[0][0],Ar1[0][1] = -3,-3

for i in range(1,14):
    for j in range(i-1,i+2):
        Ar1[i][j] = -3
Ar1[14][13],Ar1[14][14] = -3,-3
for i in range(15):
    Ar1[i][i] = 1
    
#GENERATE 10x10 array
Ar2 = np.array([[0]*10]*10,dtype = float)
Ar2[0][0],Ar2[0][1] = -2,-2

for i in range(1,9):
    for j in range(i-1,i+2):
        Ar2[i][j] = -2
Ar2[9][8],Ar2[9][9] = -2,-2
for i in range(10):
    Ar1[i][i] = 1

# 5x5 Matrix 
Ar3 = np.array([[2,-1,0,0,0],[-1,2,-1,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0],[0,0,0,-1,2]],dtype = float)

a1 = np.array([-3 for i in range (14)],dtype = float) 
b1 = np.array([1 for i in range (15)],dtype = float)
c1 = np.array([-3 for i in range (14)],dtype = float)
d1 = np.array([0.07 for i in range (15)],dtype = float)

a2 = np.array([-2 for i in range (9)],dtype = float)
b2 = np.array([1 for i in range (10)],dtype = float)
c2 = np.array([-2 for i in range (9)],dtype = float)
d2 = np.array([0.02 for i in range (10)],dtype = float)

a3 = np.array([-1,-1,-1,-1],dtype = float)
b3 = np.array([2,2,2,2,2],dtype = float)
c3 = np.array([-1,-1,-1,-1],dtype = float)
d3 = np.array([0.04,0.04,0.04,0.04,0.04],dtype = float)



print('\nMatrix 5x5')
print('============')
result3 = Thomas(a3, b3, c3, d3)
residual3 = np.subtract(np.matmul(Ar3,result3),b3)
print('\nX = ',result3)
print('\nResidual =',residual3)


print('\nMatrix 10x10')
print('==============')
result2 = Thomas(a2, b2, c2, d2)
residual2 = np.subtract(np.matmul(Ar2,result2),b2)
print('\nX = ',result2)
print('\nResidual =',residual2)

print('\nMatrix 15x15')
print('==============')
result1 = Thomas(a1, b1, c1, d1)
residual1 = np.subtract(np.matmul(Ar1,result1),b1)
print('\nX = ',result1)
print('\nResidual =',residual1)



Matrix 5x5

X =  [0.1  0.16 0.18 0.16 0.1 ]

Residual = [-0.06 -0.12 -0.14 -0.12 -0.06]

Matrix 10x10

X =  [ 0.00434783 -0.00782609 -0.01826087 -0.01130435  0.0026087   0.0026087
 -0.01130435 -0.01826087 -0.00782609  0.00434783]

Residual = [0.0026087  0.05130435 0.09304348 0.06521739 0.00956522 0.00956522
 0.06521739 0.09304348 0.05130435 0.0026087 ]

Matrix 15x15

X =  [-0.07030263 -0.04676754  0.03138011  0.03389425 -0.04341536 -0.07169937
 -0.00381776  0.04709345 -0.00381776 -0.07169937 -0.04341536  0.03389425
  0.03138011 -0.04676754 -0.07030263]

Residual = [0.14030263 0.11676754 0.03861989 0.03610575 0.11341536 0.14169937
 0.07381776 0.02290655 0.07381776 0.14169937 0.11341536 0.03610575
 0.03861989 0.11676754 0.14030263]


In [170]:
print(Ar3,'\n\n',Ar2,'\n\n',Ar1)

[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2.]] 

 [[-2. -2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-2. -2. -2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -2. -2. -2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -2. -2. -2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -2. -2. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -2. -2. -2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -2. -2. -2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -2. -2. -2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -2. -2. -2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -2. -2.]] 

 [[ 1. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-3.  1. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -3.  1. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -3.  1. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -3.  1. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -3.  1. -3.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -3.  1. -3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 

In [103]:
a= [[0]*10]*10

In [104]:
a

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [124]:
Ar1 = np.array([[0]*15]*15,dtype=float)
Ar1[0][0],Ar1[0][1] = -3,-3

for i in range(1,14):
    for j in range(i-1,i+2):
        Ar1[i][j] = -3
Ar1[14][13],Ar1[14][14] = -3,-3
print(Ar1)

[[-3. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-3. -3. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -3. -3. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -3. -3. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -3. -3. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -3. -3. -3.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -3. -3. -3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -3. -3. -3.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -3. -3. -3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -3. -3. -3.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -3. -3. -3.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -3. -3. -3.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -3. -3. -3.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -3. -3. -3.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -3. -3.]]


In [ ]:
Ar1 = np.array([[0]*15]*15,dtype=float)
Ar1[0][0],Ar1[0][1] = -3,-3

for i in range(1,14):
    for j in range(i-1,i+2):
        Ar1[i][j] = -3
Ar1[14][13],Ar1[14][14] = -3,-3

Ar2 = np.array([[2,1,0,0,0,0,0,0,0,0],[1,3,2,0,0,0,0,0,0,0],[0,1,3,1,0,0,0,0,0,0],[0,0,7,2,6,0,0,0,0,0],[0,0,0,6,2,1,0,0,0,0],[0,0,0,0,3,4,3,0,0,0],[0,0,0,0,0,8,1,5,0,0],[0,0,0,0,0,0,6,2,7,0],[0,0,0,0,0,0,0,5,4,3],[0,0,0,0,0,0,0,0,4,5]],dtype=float)   
Ar3 = np.array([[2,-1,0,0,0],[-1,2,-1,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0],[0,0,0,-1,2]],dtype=float)

a1 = np.array([-3 for i in range (14)],dtype= float) 
b1 = np.array([-3 for i in range (15)],dtype = float)
c1 = np.array([-3 for i in range (14)],dtype = float)
d1 = np.array([1 for i in range (15)],dtype = float)

a2 = np.array([1,1,7,6,3,8,6,5,4],dtype = float)
b2 = np.array([2,3,3,2,2,4,1,2,4,5],dtype = float)
c2 = np.array([1,2,1,6,1,3,5,7,3],dtype = float)
d2 = np.array([1,2,6,34,10,1,4,22,25,3],dtype = float)

a3 = np.array([-1,-1,-1,-1],dtype = float)
b3 = np.array([2,2,2,2,2],dtype = float)
c3 = np.array([-1,-1,-1,-1])
d3 = np.array([0.04,0.04,0.04,0.04,0.04])



print('\nMatrix 5x5')
print('========')
result3 = Thomas(a3, b3, c3, d3)
residual3 = np.subtract(np.matmul(Ar3,result3),b3)
print('Vector x = ',result3)
print('Ax-b =',residual3)


print('\nMatrix 10x10')
print('========')
result2 = Thomas(a2, b2, c2, d2)
residual2 = np.subtract(np.matmul(Ar2,result2),b2)
print('Vector x = ',result2)
print('Ax-b =',residual2)

print('\nMatrix 15x15')
print('========')
result1 = Thomas(a1, b1, c1, d1)
residual1 = np.subtract(np.matmul(Ar1,result1),b1)
print('Vector x = ',result1)
print('Ax-b =',residual1)
